image: openjdk:8-jdk

variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"
# ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/wr-*.jar"
# ARTIFACTS: "$CI_PROJECT_DIR/WaterResources-*.jar"

cache:
 paths:
 - $CACHE_DIR
 - $CACHE_DIR2
 key: "$CI_BUILD_REF_NAME"
 untracked: false

stages:
- deploy
    
deploy:
  stage: deploy
  script:
  - chmod +x ./gradlew
  - ./gradlew clean
  - ./gradlew build
  when: manual
#  - cp $ORIG_ARTIFACTS .
# - apt-get update
# - apt-get install rename
# - rename 's/wr/WaterResources/' *.jar
# artifacts:
#   name: "WaterResources-1.12.2"
#   paths:
#   - $ARTIFACTS